quarkus:
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  datasource:
    jdbc:
      idle-removal-interval: 50M
      max-lifetime: 50M
      max-size: 500
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sb}?autoReconnect=true&useSSL=false
    username: ${DB_USER:sb}
    password: ${DB_PASSWORD:123}
    db-kind: postgresql