services:
  postgres:
    image: postgres:15
    container_name: db_sb
    environment:
      POSTGRES_DB: ${DB_NAME:-sb}
      POSTGRES_USER: ${DB_USER:-sb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sb-network

volumes:
  postgres_data:

networks:
  sb-network: