services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sb
      - SPRING_DATASOURCE_USERNAME=sb
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: sb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sb
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: sb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sb"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local